# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/landmark.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'schema/landmark.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schema/landmark.proto\x12\x07mj.sign\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\xb8\x01\n\rLandmarkFrame\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12#\n\tleft_hand\x18\x02 \x03(\x0b\x32\x10.mj.sign.Point3D\x12$\n\nright_hand\x18\x03 \x03(\x0b\x32\x10.mj.sign.Point3D\x12\x1e\n\x04pose\x18\x04 \x03(\x0b\x32\x10.mj.sign.Point3D\x12&\n\x0c\x66\x61\x63\x65_contour\x18\x05 \x03(\x0b\x32\x10.mj.sign.Point3D\"O\n\x11\x43lientStreamChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12&\n\x06\x66rames\x18\x02 \x03(\x0b\x32\x16.mj.sign.LandmarkFrame\"[\n\x11TranslationResult\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x42#\n\x12\x63om.mj.sign.protosB\rLandmarkProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.landmark_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.mj.sign.protosB\rLandmarkProto'
  _globals['_POINT3D']._serialized_start=34
  _globals['_POINT3D']._serialized_end=76
  _globals['_LANDMARKFRAME']._serialized_start=79
  _globals['_LANDMARKFRAME']._serialized_end=263
  _globals['_CLIENTSTREAMCHUNK']._serialized_start=265
  _globals['_CLIENTSTREAMCHUNK']._serialized_end=344
  _globals['_TRANSLATIONRESULT']._serialized_start=346
  _globals['_TRANSLATIONRESULT']._serialized_end=437
# @@protoc_insertion_point(module_scope)
