#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
PROTOC_BIN="${PROTOC_BIN:-protoc}"
DART_PLUGIN="${DART_PROTOC_PLUGIN:-protoc-gen-dart}"
PROTO_FILE="$ROOT_DIR/sign/common/schema/landmark.proto"

if ! command -v "$PROTOC_BIN" >/dev/null 2>&1; then
  echo "protoc is required. Install Protocol Buffers compiler or set PROTOC_BIN." >&2
  exit 127
fi

if ! command -v "$DART_PLUGIN" >/dev/null 2>&1; then
  echo "protoc-gen-dart is required for Flutter output." >&2
  echo "Install it with: dart pub global activate protoc_plugin" >&2
  echo "Then make sure the pub cache bin directory is on PATH." >&2
  exit 127
fi

echo "Using $("$PROTOC_BIN" --version)"

cp "$PROTO_FILE" "$ROOT_DIR/sign/backend/bridge/src/main/proto/landmark.proto"

"$PROTOC_BIN" \
  -I "$ROOT_DIR/sign/common" \
  --python_out="$ROOT_DIR/sample/backend/model_server" \
  "$PROTO_FILE"

"$PROTOC_BIN" \
  -I "$ROOT_DIR/sign/common" \
  "--plugin=protoc-gen-dart=$DART_PLUGIN" \
  --dart_out="$ROOT_DIR/sign/embedded/lib/src/generated" \
  "$PROTO_FILE"

if [ "${RUN_GRADLE:-0}" = "1" ]; then
  (cd "$ROOT_DIR/sign/backend/bridge" && ./gradlew generateProto)
else
  echo "Spring Java protobuf output is generated by Gradle during build."
  echo "Set RUN_GRADLE=1 to run ./gradlew generateProto as part of this script."
fi

echo "Protobuf regeneration complete."
